"""The ``ExtractedField[T]`` wrapper.

Every field in an extraction schema is an :class:`ExtractedField` so the LLM is
forced to provide three things together: a typed ``value``, a numeric ``confidence``
in ``[0, 1]``, and a ``source_chunk_id`` pointing at the chunk that justifies the
extraction. The orchestrator (``backend.app.extract``) further verifies that every
``source_chunk_id`` was in the supplied context — a fabricated id is a hard failure.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ExtractedField[T](BaseModel):
    """A single field in a schema-constrained extraction.

    The Pydantic schema generated by :py:meth:`pydantic.BaseModel.model_json_schema`
    inlines the bounds on ``confidence`` and the type of ``value``, so the prompt
    can hand the schema to the LLM verbatim without further description.
    """

    model_config = ConfigDict(extra="forbid")

    value: T
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model self-reported confidence in this field, in [0, 1].",
    )
    source_chunk_id: int = Field(
        ...,
        ge=1,
        description=(
            "Id of the chunk in the supplied context that justifies this value. "
            "Must reference a chunk passed to the extractor."
        ),
    )
